#!/usr/local/bin/node

/**
 * Usage: "./utils/build plan us-east-2-dev" or "./utils/build apply us-east-2-dev"
 */

const exec = require('child_process').exec;

const [ tfCommand, tfEnv ] = process.argv.slice(-2);
const stateFile = `${process.env.MTG_STATE}/${tfEnv}.tfstate`;
const varFile = `./config/${tfEnv}.tfvars`;
const command = `terraform ${tfCommand} --state=${stateFile} --var-file=${varFile}`;

const tfExec = exec(command);

tfExec.stdout.pipe(process.stdout);
tfExec.stderr.pipe(process.stderr);
